plt.figure(figsize=(12, 6))
plt.plot(fitness_data['Day'], fitness_data['TotalSteps'], label='Steps', marker='o', color='blue')
plt.plot(fitness_data['Day'], fitness_data['Calories'], label='Calories Burned', marker='o', color='red')
plt.xlabel('Day')
plt.ylabel('Count')
plt.title('Steps and Calories Burned Over 30 Days')
plt.grid(True)
plt.legend()
plt.show()
